import type { Metadata } from 'next';
import styles from './menu.module.scss';
import NavMenu from '../components/navMenu/page';

export const metadata: Metadata = {
  title: 'DashBunny - POS',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={styles.flex}>
      <NavMenu />
      {children}
    </div>
  );
}
