import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import HorizontalNav from './components/horizontalNav';

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'DashBunny - POS',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr" className={`${pretendard.variable}`}>
      <body className={`${pretendard.variable} antialiased`}>
        <HorizontalNav />
        {children}
      </body>
    </html>
  );
}
