import type { Metadata } from 'next';
import styles from './coupon.module.scss';
import NavCoupon from '../components/navCoupon/page';

export const metadata: Metadata = {
  title: 'DashBunny - POS',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
};

export default function couponLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={styles.flex}>
      <NavCoupon />
      {children}
    </div>
  );
}
