import type { Metadata } from 'next';
import NavDefault from '../components/navDefault/page';
import styles from './default.module.scss';

export const metadata: Metadata = {
  title: 'DashBunny - POS',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={styles.flex}>
      <NavDefault />
      {children}
    </div>
  );
}
